---

- name: Install docker
  become: yes
  package:
    name:
      - docker.io
      - docker-compose-v2
    state: present

- name: Start and enable Docker service
  become: yes
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add 'admin' to the docker group
  become: yes
  ansible.builtin.user:
    name: admin
    groups: docker
    append: yes
